### PR TITLE
Small intro and background, target audience for this course material …

### PR DESCRIPTION
**Pull request by rajakvk**
…added.

### CODE REVIEW

**Review by abinavseelan — COMMENTED** [review]
Hey. Thank you so much for the PR 🙇 

The repository is for general use however, not just for JS Meetup BGLR. 🙂 

But that being said, the content can be contributed to, of course :smile:

**Comment by rajakvk** [comment]
Whatever but we need some introduction. People visiting this repo needs to know what to expect.

**Comment by abinavseelan** [comment]
> People visiting this repo needs to know what to expect.

Of course! But the current changes don't reflect the intent of this repo right? 🙂

**Comment by rajakvk** [comment]
What i'm trying to say is that you don't need to take my changes but add whatever change you want to add. Overall we need a nice, short description about the project in the home page. Thats it.

**Comment by rajakvk** [comment]
bye

**Pull request closed without merging**
